### PR TITLE
Upgrade logstash to 5.1.2

### PR DESCRIPTION
**Pull request by tarvip**
Also used updated logstash-output-dogstasd plugin from https://github.com/salemove/logstash-output-dogstatsd (public version is not compatible with 5.x)

### CODE REVIEW

**Comment by willmore** [comment]
Can't we pull the gem from the git repo as part of the build process?
I don't like how we're adding the artifact to this repo.

**Comment by willmore** [comment]
Why are we upgrading to 5.1.2?

**Comment by tarvip** [comment]
I'm upgrading because I want to try new elasticsearch output plugin. 
https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/CHANGELOG.md#530
Initially I tried to upgrade only elasticsearch plugin, but it didn't work (although it should be compatible with logstash 2.4.1).

At the moment logstash sometimes gets stuck:
```
{:timestamp=>"2017-01-30T08:47:43.815000+0000", :message=>"[503] {\"error\":{\"root_cause\":[{\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent]
 Data too large, data for [<http_request>] would be larger than limit of [1478832947/1.3gb]\",\"bytes_wanted\":1478838316,\"bytes_limit\":1478832947}],
 \"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be larger than limit of [1478832947/1.3gb]\",\
 "bytes_wanted\":1478838316,\"bytes_limit\":1478832947},\"status\":503}", :class=>"Elasticsearch::Transport::Transport::Errors::ServiceUnavailable", 
```

I'm hoping that 20MB chunk solves this issue.

**Comment by tarvip** [comment]
> Can't we pull the gem from the git repo as part of the build process?

I will try this.

**Comment by tarvip** [comment]
Updated.

**Pull request merged**
